//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Appointment
{
    public int Id { get; set; }
    public System.DateTime Date { get; set; }
    public System.TimeSpan Time { get; set; }
    public int DoctorID { get; set; }
    public int PatientID { get; set; }
    public string Description { get; set; }

    public virtual Doctor Doctor { get; set; }
    public virtual Patient Patient { get; set; }
}

public partial class Department
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {
        this.Doctors = new HashSet<Doctor>();
    }

    public int Id { get; set; }
    public int HospitalID { get; set; }
    public string Specialization { get; set; }
    public string DepartmentEmail { get; set; }
    public string DepartmentPhone { get; set; }

    public virtual Hospital Hospital { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Doctor> Doctors { get; set; }
}

public partial class Doctor
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Doctor()
    {
        this.Appointments = new HashSet<Appointment>();
        this.Patients = new HashSet<Patient>();
    }

    public int Id { get; set; }
    public int DepartmentID { get; set; }
    public string Name { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Appointment> Appointments { get; set; }
    public virtual Department Department { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Patient> Patients { get; set; }
}

public partial class Email
{
    public int Id { get; set; }
    public string Text { get; set; }
    public string Date { get; set; }
    public System.TimeSpan Time { get; set; }
    public string TO { get; set; }
    public string FROM { get; set; }
}

public partial class Hospital
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Hospital()
    {
        this.Departments = new HashSet<Department>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string ContactEmail { get; set; }
    public string ContactPhone { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Department> Departments { get; set; }
}

public partial class Patient
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Patient()
    {
        this.Appointments = new HashSet<Appointment>();
    }

    public int Id { get; set; }
    public int DoctorID { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Appointment> Appointments { get; set; }
    public virtual Doctor Doctor { get; set; }
}
